'use client'
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8L8UtewVLhK
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { useState } from "react"

export function Component() {
  return (
    <div
      key="1"
      className="flex flex-col min-h-screen bg-cover bg-center bg-black text-white"
      style={{
        backgroundImage:
          '"""\\"\\"\\\\"\\\\"\\\\"\\\\"url(\\\\"/placeholder.svg?height=1080&width=1920\\\\")\\\\"\\\\"\\"\\""',
      }}
    >
      <header className="px-4 lg:px-6 h-14 flex items-center bg-black backdrop-filter backdrop-blur-lg bg-opacity-60" style={{
        position: 'fixed',
        left: 0,
        right: 0,
        top: 0,
      }}>
        <Link className="flex items-center justify-center" href="#">
          <BuildingIcon className="h-6 w-6" />
        &nbsp;
        <span className="hidden md:block"> Allan_the_Agent</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Home
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#properties">
            Properties
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#about">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#contact">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-36 xl:py-48">
          <div className="containe px-4 md:px-6 m-auto">
            <div className="flex flex-col items-center space-y-3 text-center">
              <div className="space-y-2">
                <h1 className="text-4xl tracking-tighter md:text-5xl lg:text-8xl font-custom ml-[-100px] md:ml-[-250px]">
                  <div className="sparkle text-shadow-white" style={{
                    color: '#cfb53b'
                  }}>
                    Turn &nbsp; Your &nbsp; Dream
                  </div>
                  <div className="ml-[200px] md:ml-[500px] sparkle text-shadow-white" style={{
                    marginTop: 50,
                    color: '#cfb53b'
                  }}>
                    Into &nbsp; An &nbsp; Address...
                  </div>
                </h1>
                <div className="h-[20px]"/>
                <img
                  alt=""
                  className="mx-auto"
                  height="300"
                  src="/BLVD.png"
                  width="400"
                  style={{
                  }}
                />
                <img
                  alt=""
                  className="w-48 h-48 my-50 mx-auto"
                  height="300"
                  src="/fdg.png"
                  width="400"
                  style={{
                    transform: 'scale(0.5)'
                  }}
                />
                <img
                  alt="Allan"
                  className="w-48 h-48 my-50 rounded-full mx-auto"
                  height="240"
                  src="/allan2.png"
                  style={{
                    aspectRatio: "240/240",
                    objectFit: "cover",
                  }}
                  width="240"
                />
                <div className="h-[10px]"/>
                <p className="text-yellow-400 text-3xl font-playfair font-bold">Allan Sekiranda</p>
                <p className="text-gray-400 text-xl"> DRE#02221040</p>
                <div className="h-[50px]"/>
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                  Find your dream home!
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-400 md:text-xl">
                  Search from thousands of properties in your area
                </p>
                <form className="w-full max-w-sm mx-auto mt-4">
                  <Input className="w-full" placeholder="Search for properties..." type="text" />
                </form>
              </div>
            </div>
          </div>
        </section>
        <section id='properties' className="w-full py-12 md:py-24 lg:py-32 bg-gray-900">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Featured Properties</h2>
            <div className="grid grid-cols-3 gap-4 mt-8">
              <Card>
                <CardHeader>
                  <CardTitle>New Listings</CardTitle>
                </CardHeader>
                <CardContent>
                  <img
                    alt="Luxury Villa"
                    height="300"
                    src="/comingsoon.jpeg"
                    style={{
                      aspectRatio: "400/300",
                      objectFit: "cover",
                    }}
                    width="400"
                  />
                </CardContent>
                <CardFooter>
                  <Button>View Listings</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>For Lease</CardTitle>
                </CardHeader>
                <CardContent>
                  <img
                    alt="For Lease"
                    height="300"
                    src="/comingsoon.jpeg"
                    style={{
                      aspectRatio: "400/300",
                      objectFit: "cover",
                    }}
                    width="400"
                  />
                </CardContent>
                <CardFooter>
                  <Button>View Listings</Button>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section id='about' className="w-full py-12 md:py-24 lg:py-24">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">About Me</h2>
            <p className="mt-4 max-w-[600px] text-yellow-400 md:text-xl lg:text-base xl:text-xl">
              I am a dedicated real estate professional committed to providing the best service to my clients.
            </p>
            <p className="mt-4 max-w-[600px] text-yellow-400 md:text-xl lg:text-base xl:text-xl">
              I follow the real estate market very closely, and I am well equipped to help you through the process of
              buying or selling your home.
            </p>
            <p className="mt-4 max-w-[600px] text-yellow-400 md:text-xl lg:text-base xl:text-xl">
              If you have any questions about buying, selling, or investing, I would love to speak with you about your
              real estate needs!
            </p>
          </div>
        </section>
        <section id='contact' className="w-full">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Contact</h2>
            <div className="mt-5 mb-20">
              <div style={{
                display: 'flex',
              }}>
                <img src={'/insta.png'} className="w-7 h-7"/>
                &nbsp;
                <a className="text-pink-400" style={{
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'center',
                  textDecoration: 'underline',
                }} href={'https://www.instagram.com/allan_the_agent'}>Allan_the_Agent</a>
              </div>
              <div style={{
                display: 'flex',
              }}>
                <img src={'mail.jpg'} className="w-7 h-7"/>
                &nbsp;
                <a className="text-pink-400" style={{
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'center',
                  textDecoration: 'underline',
                }}href={`mailto:asekiranda@blvdestate.com?subject=Real Estate Inquiry`}>asekiranda@blvdestate.com</a>
              </div>
              <div style={{
                display: 'flex',
              }}>
                <img src={'/tiktok.jpg'} className="w-7 h-7"/>
                &nbsp;
                <a className="text-pink-400" style={{
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'center',
                  textDecoration: 'underline',
                }}href={`https://www.tiktok.com/@allanseki`}>allanseki</a>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-black backdrop-filter backdrop-blur-lg bg-opacity-60">
        <p className="text-xs text-gray-400">© Real Estate Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}


function BuildingIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="20" x="4" y="2" rx="2" ry="2" />
      <path d="M9 22v-4h6v4" />
      <path d="M8 6h.01" />
      <path d="M16 6h.01" />
      <path d="M12 6h.01" />
      <path d="M12 10h.01" />
      <path d="M12 14h.01" />
      <path d="M16 10h.01" />
      <path d="M16 14h.01" />
      <path d="M8 10h.01" />
      <path d="M8 14h.01" />
    </svg>
  )
}
